### ISSUE TITLE
Flake-Id generation has compiled dependencies

### ISSUE THREAD

**Issue by Downchuck** [LeanKit-Labs/riaktive#16]
Currently flake requires basejump and murmurhash3 to be compiled; the basejump githup page seems to call itself out as a library that's not mature for production. Both dependencies require a c++ compiler with node-gyp, making it more challenging to use this library.

It seems that the base riaktive module would be easier to install (more compatible with Windows) if these dependencies were moved into a different module.

**Comment by arobson** [comment]
@Downchuck - node-gyp will work fine on Windows (we actually have other things we build on Windows that require sliver). I've also recently updated the baseJump library to support both 0.10 and 0.12 Node versions.

Flake Ids are in use in this library because those are honestly going to provide the best long-term performance when used with storage systems that have to keep keys ordered. (another way to say this is: randomized keys can cause problems on insertion and will cause churn due to rebalancing)

I may be able to change things such that there's an id strategy that anyone using Riaktive can provide and just let folks plug in sliver if they choose to.

Also, be aware that the latest version of riaktive on NPM has a few changes, I just need to get the PRs merged in to reflect those.

**Comment by Downchuck** [comment]
Fixed in commit ffe09ec8bfd41c648ccf15bba07a260875e3ec22
